// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
#pragma warning disable CA1707

namespace RacePredictor.Core.ML;

public partial class RacePredictor
{
    private static readonly string ModelPath = Path.GetFullPath("RacePredictor.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine =
        new(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        var mlModel = mlContext.Model.Load(ModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    ///     Use this method to predict on <see cref="ModelInput" />.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns>
    ///     <seealso cref=" ModelOutput" />
    /// </returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    /// <summary>
    ///     model input class for RacePredictor.
    /// </summary>

    #region model input class

    public class ModelInput
    {
        [LoadColumn(11)]
        [ColumnName(@"DistanceInMeters")]
        public float DistanceInMeters { get; set; }

        [LoadColumn(12)]
        [ColumnName(@"WeightInPounds")]
        public float WeightInPounds { get; set; }

        [LoadColumn(13)]
        [ColumnName(@"Surface_AllWeather")]
        public float Surface_AllWeather { get; set; }

        [LoadColumn(14)]
        [ColumnName(@"Surface_Dirt")]
        public float Surface_Dirt { get; set; }

        [LoadColumn(15)]
        [ColumnName(@"Surface_Turf")]
        public float Surface_Turf { get; set; }

        [LoadColumn(16)]
        [ColumnName(@"Going_Firm")]
        public float Going_Firm { get; set; }

        [LoadColumn(17)]
        [ColumnName(@"Going_Good")]
        public float Going_Good { get; set; }

        [LoadColumn(18)]
        [ColumnName(@"Going_Good_To_Firm")]
        public float Going_Good_To_Firm { get; set; }

        [LoadColumn(19)]
        [ColumnName(@"Going_Good_To_Soft")]
        public float Going_Good_To_Soft { get; set; }

        [LoadColumn(20)]
        [ColumnName(@"Going_Heavy")]
        public float Going_Heavy { get; set; }

        [LoadColumn(21)]
        [ColumnName(@"Going_Soft")]
        public float Going_Soft { get; set; }

        [LoadColumn(22)]
        [ColumnName(@"RaceType_Flat")]
        public float RaceType_Flat { get; set; }

        [LoadColumn(23)]
        [ColumnName(@"RaceType_Hurdle")]
        public float RaceType_Hurdle { get; set; }

        [LoadColumn(24)]
        [ColumnName(@"RaceType_Other")]
        public float RaceType_Other { get; set; }

        [LoadColumn(25)]
        [ColumnName(@"RaceType_SteepleChase")]
        public float RaceType_SteepleChase { get; set; }

        [LoadColumn(26)]
        [ColumnName(@"LastRaceDistanceInMeters")]
        public float LastRaceDistanceInMeters { get; set; }

        [LoadColumn(27)]
        [ColumnName(@"LastRaceWeightInPounds")]
        public float LastRaceWeightInPounds { get; set; }

        [LoadColumn(28)]
        [ColumnName(@"LastRaceSpeed")]
        public float LastRaceSpeed { get; set; }

        [LoadColumn(29)]
        [ColumnName(@"DaysRested")]
        public float DaysRested { get; set; }

        [LoadColumn(30)]
        [ColumnName(@"LastRaceAvgRelFinishingPosition")]
        public float LastRaceAvgRelFinishingPosition { get; set; }

        [LoadColumn(31)]
        [ColumnName(@"LastRaceSurface_AllWeather")]
        public float LastRaceSurface_AllWeather { get; set; }

        [LoadColumn(32)]
        [ColumnName(@"LastRaceSurface_Dirt")]
        public float LastRaceSurface_Dirt { get; set; }

        [LoadColumn(33)]
        [ColumnName(@"LastRaceSurface_Turf")]
        public float LastRaceSurface_Turf { get; set; }

        [LoadColumn(34)]
        [ColumnName(@"LastRaceGoing_Good")]
        public float LastRaceGoing_Good { get; set; }

        [LoadColumn(35)]
        [ColumnName(@"LastRaceGoing_Good_To_Soft")]
        public float LastRaceGoing_Good_To_Soft { get; set; }

        [LoadColumn(36)]
        [ColumnName(@"LastRaceGoing_Soft")]
        public float LastRaceGoing_Soft { get; set; }

        [LoadColumn(37)]
        [ColumnName(@"LastRaceGoing_Good_To_Firm")]
        public float LastRaceGoing_Good_To_Firm { get; set; }

        [LoadColumn(38)]
        [ColumnName(@"LastRaceGoing_Firm")]
        public float LastRaceGoing_Firm { get; set; }

        [LoadColumn(39)]
        [ColumnName(@"LastRaceGoing_Heavy")]
        public float LastRaceGoing_Heavy { get; set; }

        [LoadColumn(40)]
        [ColumnName(@"LastRaceRaceType_Other")]
        public float LastRaceRaceType_Other { get; set; }

        [LoadColumn(41)]
        [ColumnName(@"LastRaceRaceType_Hurdle")]
        public float LastRaceRaceType_Hurdle { get; set; }

        [LoadColumn(42)]
        [ColumnName(@"LastRaceRaceType_SteepleChase")]
        public float LastRaceRaceType_SteepleChase { get; set; }

        [LoadColumn(43)]
        [ColumnName(@"LastRaceRaceType_Flat")]
        public float LastRaceRaceType_Flat { get; set; }

        [LoadColumn(44)]
        [ColumnName(@"JockeyNumberOfPriorRaces")]
        public float JockeyNumberOfPriorRaces { get; set; }

        [LoadColumn(45)]
        [ColumnName(@"DaysSinceJockeyLastRaced")]
        public float DaysSinceJockeyLastRaced { get; set; }

        [LoadColumn(46)]
        [ColumnName(@"JockeyWinPercentage")]
        public float JockeyWinPercentage { get; set; }

        [LoadColumn(47)]
        [ColumnName(@"JockeyTop3Percentage")]
        public float JockeyTop3Percentage { get; set; }

        [LoadColumn(48)]
        [ColumnName(@"JockeyAvgRelFinishingPosition")]
        public float JockeyAvgRelFinishingPosition { get; set; }

        [LoadColumn(49)]
        [ColumnName(@"Speed")]
        public float Speed { get; set; }
    }

    #endregion

    /// <summary>
    ///     model output class for RacePredictor.
    /// </summary>

    #region model output class

    public class ModelOutput
    {
        [ColumnName(@"DistanceInMeters")] public float DistanceInMeters { get; set; }

        [ColumnName(@"WeightInPounds")] public float WeightInPounds { get; set; }

        [ColumnName(@"Surface_AllWeather")] public float SurfaceAll_Weather { get; set; }

        [ColumnName(@"Surface_Dirt")] public float Surface_Dirt { get; set; }

        [ColumnName(@"Surface_Turf")] public float Surface_Turf { get; set; }

        [ColumnName(@"Going_Firm")] public float Going_Firm { get; set; }

        [ColumnName(@"Going_Good")] public float Going_Good { get; set; }

        [ColumnName(@"Going_Good_To_Firm")] public float Going_Good_To_Firm { get; set; }

        [ColumnName(@"Going_Good_To_Soft")] public float Going_Good_To_Soft { get; set; }

        [ColumnName(@"Going_Heavy")] public float Going_Heavy { get; set; }

        [ColumnName(@"Going_Soft")] public float Going_Soft { get; set; }

        [ColumnName(@"RaceType_Flat")] public float RaceType_Flat { get; set; }

        [ColumnName(@"RaceType_Hurdle")] public float RaceType_Hurdle { get; set; }

        [ColumnName(@"RaceType_Other")] public float RaceType_Other { get; set; }

        [ColumnName(@"RaceType_SteepleChase")] public float RaceType_SteepleChase { get; set; }

        [ColumnName(@"LastRaceDistanceInMeters")]
        public float LastRaceDistanceInMeters { get; set; }

        [ColumnName(@"LastRaceWeightInPounds")]
        public float LastRaceWeightInPounds { get; set; }

        [ColumnName(@"LastRaceSpeed")] public float LastRaceSpeed { get; set; }

        [ColumnName(@"DaysRested")] public float DaysRested { get; set; }

        [ColumnName(@"LastRaceAvgRelFinishingPosition")]
        public float LastRaceAvgRelFinishingPosition { get; set; }

        [ColumnName(@"LastRaceSurface_AllWeather")]
        public float LastRaceSurface_AllWeather { get; set; }

        [ColumnName(@"LastRaceSurface_Dirt")] public float LastRaceSurface_Dirt { get; set; }

        [ColumnName(@"LastRaceSurface_Turf")] public float LastRaceSurface_Turf { get; set; }

        [ColumnName(@"LastRaceGoing_Good")] public float LastRaceGoing_Good { get; set; }

        [ColumnName(@"LastRaceGoing_Good_To_Soft")]
        public float LastRaceGoing_Good_To_Soft { get; set; }

        [ColumnName(@"LastRaceGoing_Soft")] public float LastRaceGoing_Soft { get; set; }

        [ColumnName(@"LastRaceGoing_Good_To_Firm")]
        public float LastRaceGoing_Good_To_Firm { get; set; }

        [ColumnName(@"LastRaceGoing_Firm")] public float LastRaceGoing_Firm { get; set; }

        [ColumnName(@"LastRaceGoing_Heavy")] public float LastRaceGoing_Heavy { get; set; }

        [ColumnName(@"LastRaceRaceType_Other")]
        public float LastRaceRaceType_Other { get; set; }

        [ColumnName(@"LastRaceRaceType_Hurdle")]
        public float LastRaceRaceType_Hurdle { get; set; }

        [ColumnName(@"LastRaceRaceType_SteepleChase")]
        public float LastRaceRaceType_SteepleChase { get; set; }

        [ColumnName(@"LastRaceRaceType_Flat")] public float LastRaceRaceType_Flat { get; set; }

        [ColumnName(@"JockeyNumberOfPriorRaces")]
        public float JockeyNumberOfPriorRaces { get; set; }

        [ColumnName(@"DaysSinceJockeyLastRaced")]
        public float DaysSinceJockeyLastRaced { get; set; }

        [ColumnName(@"JockeyWinPercentage")] public float JockeyWinPercentage { get; set; }

        [ColumnName(@"JockeyTop3Percentage")] public float JockeyTop3Percentage { get; set; }

        [ColumnName(@"JockeyAvgRelFinishingPosition")]
        public float JockeyAvgRelFinishingPosition { get; set; }

        [ColumnName(@"Speed")] public float Speed { get; set; }

        [ColumnName(@"Features")] public float[] Features { get; set; } = Array.Empty<float>();

        [ColumnName(@"Score")] public float Score { get; set; }
    }

    #endregion
}
